

; typedef struct _Player
; {
; 	uint8_t status;
;     uint32_t  currentTick;
; 	uint32_t  lastScoreTick;
; 	uint8_t  decayGenTick;
;     uint8_t* scorePointer;
;     Synthesizer mainSynthesizer;
; } Player;

pStatus=0
pCurrentTick_b3=1
pCurrentTick_b2=2
pCurrentTick_b1=3
pCurrentTick_b0=4
pLastScoreTick_b3=5
pLastScoreTick_b2=6
pLastScoreTick_b1=7
pLastScoreTick_b0=8
pDecayGenTick=9
pScorePointer=10
pMainSynthesizer=11

